### ISSUE TITLE
[Question] Time sync

### ISSUE THREAD

**Issue by astromediaonly** [insthync/LiteNetLibManager#10]
Hi, i figured it will be better to ask "profesional" :) - What is best way to handle sync of time related things on client and server with LiteNetLibManager like skill CD's? I had tryed to save timestamp for skill when it was casted and sync it trouh synclist to client and both on server and client handle CD based on that timestamp when was casted + duration. This i thought will be most stable and it is working but it seems like its having issues with times less than 1-2 secs so i had probably missed some detail.

I will eventually have more timers + need to sync daytime cycle (tho this one is probably special case and will not require this ammount of precision) so if you can give me some advice releated to that it would be very appretiated. Its not that important right now (im still fighting with extreeme amount of animations i need to implement) but its probably better to ask in advance :) (i hope you dont mind - if there is nothing for handling those cases inside your library its probably fine, i will fix it one day somehow my self probably but sometimes its better to ask somebody who was already dealing with same type of stuff instead of inventing wheel again if you know what i mean :) )

**Comment by insthync** [comment]
You may see ping and server time sync scripts in `LiteNetLibGameManager` → `SendClientPing` which before send request from client to server , it will store {current timestamp} as {request timestamp} at client then request for server to pong back, then when server pong back it will use {current timestamp} - {request timestamp} to find difference time which is [RTT](https://en.wikipedia.org/wiki/Round-trip_delay_time).

Then we can use RTT to adjust synced server time at client nearly with the server.

**Comment by astromediaonly** [comment]
I see, that is helpfull and probably all i need, thanks for pointing it out.

PS: sorry for opening so much questions but there is lot to learn, i still hope you dont mind that much and you are happy somebody is interested in this project and using it ... but if im taking too much of your time i can probably make some financial donation to compensate that if you have patreon or something if you want. Either way i hope you are ok during this worldwide crysis (i dont know how bad its in your country) and thanks again for response ... i will close this now :)
