### ISSUE TITLE
[Question] Looong distance sync optimisation

### ISSUE THREAD

**Issue by astromediaonly** [insthync/LiteNetLibManager#11]
Hi, may i ask quick question after some time? :) ... i never know what is proper channel to do that, hopefully its ok here. Im trying to figure out if this library is suitable for case when i have position driven by some third party stuff due avoiding floating point precission problems with large maps (i have position stored elsewhere than transform - im not sure if thats relevant) and what i want is to sync only object/player with positional variables close enough to current player - I know about two features - those subscribers and there is also some visibility checker if i remember correctly. My question is - what is best approach for something like that? I can do it from scratch the old fashioned way with commands if its too problematic but that spawning logic with automatic syncing of vars and lists is very helpfull :)

PS: Im very greatfull you found some time to expand docs, thanks for that. There are still some thing not that clear to me (like when subscribers gets rebuilded/recalculated) but overall there is lot of new usefull info there. 👍

**Comment by insthync** [comment]
You may create a new class which working like `LiteNetLibVisibleChecker` which will check positions of an object and decide that the object should sync to other client or not.

**Comment by astromediaonly** [comment]
I thought it can help me but to be honest i did not figured yet what it does exactly - i only know it exists because i saw it in MMO Kit :). Is it documented somewhere? I guess it limits player visibility of networked objects to its range but there is lot of stuff happening in that class. Reading through it leaves me with lot of questions like "Why it touches renderers?" (if its on server it should take into consideration all players and not only one, if its on client than it should probably destroy those objects and not just hide them), "how it tells to player he should not see anything before specifying what he can se?" (because if i understand it right default state is to sync everything no matter the range) and so. I hope it makes sense :)

**Comment by astromediaonly** [comment]
I was working on other projects but Im still here :) ... It was not in hurry and you seemed very bussy so I left it open and hoped I will get some answers one day when you will have more time for it but now I see you closed it without response (and one my other issue left here with similar intention) - can I know why?

**Comment by insthync** [comment]
Interest management system was changed, now it will be handled by interest manager class. It still touches renderers at server because it will stop updating when game objects deactivated.

**Comment by astromediaonly** [comment]
I see, thanks for info, I will try to update LiteNetLibManager in my project (during weekend probably) and see what is new. Is there some documentation/usage guide to that Interest manager yet or its still early in development?

**Comment by insthync** [comment]
It's done, but I didn't update the document yet :P, I don't expect that it will have anyone will use it :P

**Comment by astromediaonly** [comment]
I see, its not in hurry but let me know please when you do :) ... Its huge pain but it was better for me to start develop custom mmo solution (there will be so much things wrong, unsecure and unoptimised tho :D ) because of how I want/need things structured so Im using LiteNetLibManager directly instead of MMO Kit ... Im probably the only one crazy enough to try that but whatever :)

**Comment by insthync** [comment]
Develops it with .NET 5, right?

**Comment by astromediaonly** [comment]
Im not sure if I get it right but Im using Unity on .Net 4.x ... is 5 even in Unity yet? (I wonder why you are asking)

**Comment by insthync** [comment]
I thought you will develop its server by using .NET 5 and uses Unity as a client.

**Comment by astromediaonly** [comment]
I see, I was hoping to do that at start, it would be great to be able to do it but sadly I had found no good (or any other usable) way to handle map collisions .... it would require me to somehow export coliders from Unity scene into something I would be able to parse and analize in my server app and that would be huge pain.
(I did not tryed 5 yet with anything I thing ... newest version is probably 4.7 my custom webserver is in)

**Comment by astromediaonly** [comment]
Hi, so I had finaly found some time to update LiteNetLibManager in my project and now Im trying to make it work again - may I ask what is ``dataChannel`` byte used for? Its something I had to add to make communication functions work and Im not sure what it does.

**Comment by insthync** [comment]
It's LiteNetLib's data channel, you can set it as `0` if you just want to use default channel

**Comment by astromediaonly** [comment]
I see, it did not occured to me it could be LiteNetLib thing, thanks for response. With 0 everything LiteNetLibManager releated seems to work as good as before upgrade which is great. Sadly now I need to fix my stuff around networking animations which is huge pain :/ :D (and fact I cant derive from Unity's Animator does not help :/) ... But hopefully I will find soon some workaround ... Im curious how you designed that Interest manager :)

**Comment by astromediaonly** [comment]
Sorry to bother you again but I have got now weird and very intimidating stack trace somewhere from ZLogger or so and nothing is indicating what I did wrong so If you have some tips where to look in this case it would be highly appretiated - I was able to figure out only its somewhere in Assets.NetworkSpawn because that was the only code mentioned which was realy mine :) :/ ... Usually it fails in my code and its easy to diagnosticate but this? I have no clue :/ ... If not nothing is happening, I will probably figure it out eventually somehow too but I would need to take a lot of things apart to do that Im afraid so Im asking author of the library in faith it will be something stupid and easily findable I just dont have knowledge to figure out yet :) 

```
System.NullReferenceException: Object reference not set to an instance of an object
  at LiteNetLibManager.LiteNetLibBehaviour.RegisterSyncElement[T] (T element, System.Collections.Generic.List`1[T] elementList) [0x00008] in D:\_WORK\Unity Projects\MMO Core\Assets\LiteNetLibManager\Scripts\GameApi\LiteNetLibBehaviour.cs:423 
  at LiteNetLibManager.LiteNetLibBehaviour.SetupSyncElements[T] (System.Collections.Generic.List`1[T] fields, System.Collections.Generic.List`1[T] elementList) [0x0002a] in D:\_WORK\Unity Projects\MMO Core\Assets\LiteNetLibManager\Scripts\GameApi\LiteNetLibBehaviour.cs:261 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
UnityEngine.DebugLogHandler:LogFormat (UnityEngine.LogType,UnityEngine.Object,string,object[])
UnityEngine.Logger:Log (UnityEngine.LogType,object)
UnityEngine.Debug:LogError (object)
ZLogger.Providers.UnityDebugLogProcessor:Post (ZLogger.IZLoggerEntry) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Plugins/ZLogger/Unity/ZLoggerUnityLoggerProvider.cs:69)
ZLogger.AsyncProcessZLogger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Plugins/ZLogger/AsyncProcessZLogger.cs:36)
Microsoft.Extensions.Logging.Logger:<Log>g__LoggerLog|12_0<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.ILogger,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>,System.Collections.Generic.List`1<System.Exception>&,Microsoft.Extensions.Logging.FormattedLogValues&)
Microsoft.Extensions.Logging.Logger:Log<Microsoft.Extensions.Logging.FormattedLogValues> (Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,Microsoft.Extensions.Logging.FormattedLogValues,System.Exception,System.Func`3<Microsoft.Extensions.Logging.FormattedLogValues, System.Exception, string>)
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,Microsoft.Extensions.Logging.EventId,System.Exception,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:Log (Microsoft.Extensions.Logging.ILogger,Microsoft.Extensions.Logging.LogLevel,string,object[])
Microsoft.Extensions.Logging.LoggerExtensions:LogError (Microsoft.Extensions.Logging.ILogger,string,object[])
LiteNetLibManager.Logging:LogException (string,System.Exception) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/Logging.cs:32)
LiteNetLibManager.LiteNetLibBehaviour:SetupSyncElements<LiteNetLibManager.LiteNetLibSyncList> (System.Collections.Generic.List`1<System.Reflection.FieldInfo>,System.Collections.Generic.List`1<LiteNetLibManager.LiteNetLibSyncList>) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:266)
LiteNetLibManager.LiteNetLibBehaviour:CacheElements () (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:248)
LiteNetLibManager.LiteNetLibBehaviour:Setup (byte) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibBehaviour.cs:189)
LiteNetLibManager.LiteNetLibIdentity:Initial (LiteNetLibManager.LiteNetLibGameManager,bool,uint,long) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibIdentity.cs:486)
LiteNetLibManager.LiteNetLibAssets:NetworkSpawn (UnityEngine.GameObject,uint,long) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibAssets.cs:206)
MMOCore.MapServer/<DeserializeClientReadyData>d__45:MoveNext () (at D:/_WORK/Unity Projects/MMO Core/Assets/Core/Server/MapServer.cs:220)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1<bool>:Start<MMOCore.MapServer/<DeserializeClientReadyData>d__45> (MMOCore.MapServer/<DeserializeClientReadyData>d__45&) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:242)
MMOCore.MapServer:DeserializeClientReadyData (LiteNetLibManager.LiteNetLibIdentity,long,LiteNetLib.Utils.NetDataReader)
LiteNetLibManager.LiteNetLibGameManager/<SetPlayerReady>d__100:MoveNext () (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:960)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskMethodBuilder`1<bool>:Start<LiteNetLibManager.LiteNetLibGameManager/<SetPlayerReady>d__100> (LiteNetLibManager.LiteNetLibGameManager/<SetPlayerReady>d__100&) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/AsyncUniTaskMethodBuilder.cs:242)
LiteNetLibManager.LiteNetLibGameManager:SetPlayerReady (long,LiteNetLib.Utils.NetDataReader)
LiteNetLibManager.LiteNetLibGameManager/<HandleClientReadyRequest>d__69:MoveNext () (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:530)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start<LiteNetLibManager.LiteNetLibGameManager/<HandleClientReadyRequest>d__69> (LiteNetLibManager.LiteNetLibGameManager/<HandleClientReadyRequest>d__69&) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Plugins/UniTask/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:110)
LiteNetLibManager.LiteNetLibGameManager:HandleClientReadyRequest (LiteNetLibManager.RequestHandlerData,LiteNetLibManager.EmptyMessage,LiteNetLibManager.RequestProceedResultDelegate`1<LiteNetLibManager.EmptyMessage>)
LiteNetLibManager.LiteNetLibRequestHandler`2<LiteNetLibManager.EmptyMessage, LiteNetLibManager.EmptyMessage>:InvokeRequest (LiteNetLibManager.RequestHandlerData,LiteNetLibManager.RequestProceededDelegate) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/LiteNetLibRequestHandler.cs:29)
LiteNetLibManager.TransportHandler:ProceedRequest (long,LiteNetLib.Utils.NetDataReader) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/TransportHandler.cs:166)
LiteNetLibManager.TransportHandler:ReadPacket (long,LiteNetLib.Utils.NetDataReader) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/TransportHandler.cs:69)
LiteNetLibManager.LiteNetLibServer:OnServerReceive (LiteNetLibManager.TransportEventData) (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/LiteNetLibServer.cs:67)
LiteNetLibManager.LiteNetLibServer:Update () (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/LiteNetLibServer.cs:31)
LiteNetLibManager.LiteNetLibManager:FixedUpdate () (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/LiteNetLibManager.cs:108)
LiteNetLibManager.LiteNetLibGameManager:FixedUpdate () (at D:/_WORK/Unity Projects/MMO Core/Assets/LiteNetLibManager/Scripts/GameApi/LiteNetLibGameManager.cs:94)
```

**Comment by insthync** [comment]
Did you delare SyncField variables? If yes, then how they were declared?

**Comment by astromediaonly** [comment]
I have few there. This way:
```
[SerializeField]
public SyncFieldBool IsMoving = new SyncFieldBool();```

And 
```
        [DevExtMethods("OnSetup")]
        public void OnSetup_Animation()
        {
            IsMoving.onChange += OnIsMovingChange; IsMoving.deliveryMethod = LiteNetLib.DeliveryMethod.ReliableSequenced;
         }```
         
plus removing event in ondestroy but I suppose thats not relevant.
And those codes are all in parent class ( : LiteNetLibBehaviour) my spawned player character is derived from.

**Comment by insthync** [comment]
How about sync lists?

**Comment by insthync** [comment]
Because the logs saying like the sync field or sync list is null

**Comment by astromediaonly** [comment]
I see, I have those too but seems correct:
```
[SerializeField]
public LiteNetLibSyncList<CharacterItem> Items;
```

```
[DevExtMethods("OnSetup")]
void OnSetup_Items() {
    Items = new LiteNetLibSyncList<CharacterItem>();
    Items.onOperation += OnItemsChange;

    ...
}
```

Most of this stuff was working before but its some time, maybe there is something I missed ... I will keep searching ... is there any chance I could modify some code to get better insight which / how named one is wrong?

**Comment by insthync** [comment]
You should declare it like this for sure.
public LiteNetLibSyncList<CharacterItem> Items = new LiteNetLibSyncList<CharacterItem>();

I also don't know that did you call dev ext invoking function in override `OnSetup` function correctly.

**Comment by astromediaonly** [comment]
You are lifesaver, thanks so much! I was able to identify the issue - when I did rewrite as you suggested I have got different error ``ArgumentException: NetDataWriter cannot write type SpellCharacterData`` and I was home :) - I moved some data object I needed in multiple projects to dll and this one was not ``INetSerializable`` ... It was realy weird how this issue manifested but Im so glad I caught it, now it seems to work fine within regular parameters :) ... thanks again.
