### ISSUE TITLE
Setting owner makes object disapear from client

### ISSUE THREAD

**Issue by astromediaonly** [insthync/LiteNetLibManager#12]
Im calling `SetOwnerClient` on my class derived from `LiteNetLibBehavior` on server and when i do so its no longer synced to my client. Did i overlooked something? Im not sure if im supposed to use that function but i expected if i do so i will be able to change transform rotation and so from that client. Im also calling it on multiple objects in loop if its relevant.

**Comment by insthync** [comment]
You may check connection id is correct or not by logging IsOwnerClient is true after called SetOwnerClient function

**Comment by astromediaonly** [comment]
Thanks for response tho im not sure if i get it - where should i log that IsOwnerClient? It does not make sense on server from what i understand it is and on that client that object does not appear so i cant check it there as well ... sorry if im just stupid

Additional info: Im using that SetOwnerClient in DeserializeClientReadyExtra to assign all spawned objects owned by that player to him ... now im thinking - maybe its too soon? (is it safe to do that there?)

**Comment by insthync** [comment]
You may write log in Update function in the class which derived from LiteNetLibBehavior,

call SetOwnerClient in DeserializeClientReadyExtra is safe, the LiteNetLibAssets  → NetworkSpawn function also call SetOwnerClient to set owner client. You actually can set owner client when calling LiteNetLibAssets  → NetworkSpawn function

**Comment by astromediaonly** [comment]
Ok, i had loged it - on server it says True before i assign specific client as owner and then it says False. (this should be correct shouldnt it? from what i understand befor client is assigned as owner server is owner and after assigning it server is no longer owner but that client is) I cannot check on client because that object is not spawned there which is my problem as i mentioned at the beginning. What am i missing? :/

**Comment by astromediaonly** [comment]
I suppose this became deprecated because of meanwhile changes somehow too?
