### ISSUE TITLE
Are there any usage documents?

### ISSUE THREAD

**Issue by JerryLiew** [insthync/LiteNetLibManager#13]
I noticed that the usage document in  the README page is invalid.

**Comment by JerryLiew** [comment]
I think it would be better if there were some examples.

**Comment by insthync** [comment]
Try it again https://insthync.github.io/LiteNetLibManager/

**Comment by JerryLiew** [comment]
> Try it again https://insthync.github.io/LiteNetLibManager/
thanks  a lot.This page can be opened now, but it seems that it only has the following contents. Is it correct?
![chrome_rzLiz5GqrG](https://user-images.githubusercontent.com/51161678/128709285-71e54d19-e81c-46fa-9556-ec4a47d501c1.png)
