### ISSUE TITLE
Rooms Support ?

### ISSUE THREAD

**Issue by LSXPrime** [insthync/LiteNetLibManager#16]
I used this HLAPI for a Survival project and it gave a great result but when I moved to something smaller "Battle Royale FPS" with about 32-100 player per room , I got some problems , I am using it as World-Based "all players in one room , scene" but in Battle Royale  it supposed to be Room-Based "each 100 player per room" I used UNET before & PUN and both of them support Rooms & Lobby , Mirror too but this a lot easier & less complex & giving good performance .
So my Question, does **LiteNetLibManager support Rooms**  , or is Planned to be Added ?
I am trying to add using Rooms code from Mirror,UNET but I don't achieve any progress

- Sorry for all this chit-chat :)

**Comment by insthync** [comment]
It doesn't have built-in room support, I would recommend you to change how you think about the room system, you still can use Mirror or UNET (or other) for game networking. You can determine that when you run servers headlessly it is like to create a new game room, so you will have to create (or find) a room management system that works separately from game codes, which will run a new game-server when players request for it to create a new game room, there are some open-source projects which made for that purpose such as 
- https://agones.dev/site/
- https://github.com/alvyxaz/barebones-masterserver
