### ISSUE TITLE
Server not seeing clients

### ISSUE THREAD

**Issue by NFMynster** [insthync/LiteNetLibManager#3]
Hello @insthync 
I'm starting out with this library and have a few questions. I can't seem to get the clients position updated properly.

I have these two fields defined at top of my LiteNetLibBehaviour.
```
    [SerializeField]
    private LiteNetLibSyncField<Vector3> position = new LiteNetLibSyncField<Vector3>();
    [SerializeField]
    private LiteNetLibSyncField<Quaternion> rotation = new LiteNetLibSyncField<Quaternion>();
```

I'm instantiating my players by having them in the LiteLibAssets, which the Network Manager calls NetworkSpawn all, nothing modified there.

Inside Update(), I'm doing setting the field values.
```
    private void Update()
    {
        if (IsOwnerClient)
        {
            position.Value = transform.position;
            rotation.Value = transform.rotation;
        }
        else
        {
            transform.position = position.Value;
            transform.rotation = rotation.Value;
        }
    }
```

Now, I'm not sure who has ownership, but I did modify the ValidateBeforeAcces() method, as I want the clients to be able to modify their own fields as well, ie fully clientside authority. 
```
        protected override bool ValidateBeforeAccess()
        {
            return behaviour != null && behaviour.IsOwnerClient;
        }
```

**The problem is that the server ALWAYS sees the clients spawned in Vector3.zero and aren't updating their position**
The clients can see the server and the server's position & rotation updates.

Thanks a bunch.

**Comment by insthync** [comment]
Hello, you are going to sync data from client to server then server sync them to other clients right?

**Comment by NFMynster** [comment]
Yes that would be the ideal, as I would assume it would be a peer to peer alike structure else.

**Comment by NFMynster** [comment]
I am also on your MMORPG discord, in case you want to discuss this real time.

**Comment by insthync** [comment]
Okay, I will add it

**Comment by insthync** [comment]
Just added it but didn't test it yet, I remove `forOwnerOnly` and add `syncMode`, you can change this to `ClientMulticast` to make it update changes from owner-client to server

**Comment by NFMynster** [comment]
Okay, so I tested it, and the results are the same. 
Should I assign ownership somehow for the clientMulticast to work, or how? @insthync 
Spawning my players like this
`Assets.NetworkSpawn(Instantiate(gameObject.gameObject, postion, rotation));`
and it's called from within the game scene, so it should execute on joining clients.

**Comment by NFMynster** [comment]
Hello again @insthync 
I did some more debugging, and it seems like the server never receives the LiteNetLibSyncField, neither does the client actually send the value. The Serialize method is never called on the owning client.
