### ISSUE TITLE
SyncFieldIntArray does not sync if only its one value (on index) is changed

### ISSUE THREAD

**Issue by astromediaonly** [insthync/LiteNetLibManager#5]
So if you do this it does not trigger sync:
```csharp
SyncFieldIntArray myIntArray = new SyncFieldArray();
...
myIntArray.value[0] = 5;
```
Because that setter logic works only if whole array is replaced.

My solution was to add indexer like this:
```csharp
[Serializable] 
    public class SyncFieldIntArray : LiteNetLibSyncField<int[]> 
    { 
        public int this[int i] 
        { 
            get { return Value[i]; } 
            set { 
                Value[i] = value; 
                hasUpdate = true; 
                if (onChange != null) 
                    onChange.Invoke(false, Value); 
            } 
        } 
    } 
```
And then call it as myIntArray[0] = 5;

Maybe there is better way but this was not hard and works ... would be nice if some solution would be integrated so i would not need to watch for this edit every update :)

**Comment by insthync** [comment]
Just push new update, but I didn't tested it yet :P

**Comment by astromediaonly** [comment]
Oh, that was quick, thanks :) ... My solution was tested so it should be fine ... i will probably wait for new MMO Kit update and get it with it .. updating project is hell :D ... now at least i dont have to maintain that change on my side which is much appretiated ... im kinda forgetful and i would be wondering why my stuff is not working anymore after update otherwise :)

**Comment by astromediaonly** [comment]
I dont know where to ask so im asking here, i hope you dont mind - i supose when i change object property inside synclist it will not sync new values automaticaly would it? From what i understand only adding, removing and so triggers sync - is there some way to trigger sync manualy after i change values inside my object at one of indexes? I thought about setting that object again to that index but if there is some check if its different from previous value it will not work anyway and even if it would work i would like to trigger sync in a loop and its not advised to change collection items during that. And i also dont know how to check for that change event properly on client inside onOperation.

**Comment by insthync** [comment]
Synclist will update changed data when you set data to the index, for example:
`list[i] = newValue;` or you may call `Dirty` function to tell it that there are changes `list.Dirty(i);` to trigger onOperation event and send operation message to client.

**Comment by insthync** [comment]
But  `onOperation` will be  invoked, after data changed.

**Comment by astromediaonly** [comment]
That ``list.Dirty(i);`` seems to be working nicely, thanks so much ... i thought there will be something like that hidden somewhere :)
