### ISSUE TITLE
In-scene network objects aren't initialized properly

### ISSUE THREAD

**Issue by NFMynster** [insthync/LiteNetLibManager#6]
Using in-scene network objects becomes tricky, as they aren't owned by the server.
Therefor, you can't rely on the IsOwner to invoke RPCs.

Am I doing something wrong, or can I transfer the ownership over to the server?

**Comment by NFMynster** [comment]
Any thoughts? @insthync

**Comment by insthync** [comment]
IsOwner will be true when the network object was spawned for your client. To check it is run on server or not, you can use IsServer

**Comment by NFMynster** [comment]
But, IsOwnerClient is not true on either client or server, which confused me. 
Let me retest to make sure, thank you.

**Comment by insthync** [comment]
In the latest update, Server will send `Connection Id` to client to define `Client Connection Id` (See LiteNetLibGameManager.cs Line 642) after the server receives `Enter Game` message from client (See LiteNetLibGameManager.cs Line 530).

Then when Spawn network objects at server with `Assets.NetworkSpawn()`  function, you can set `Connection Id` to define that the network object is spawn for which client which will be the owner client (See LiteNetLibGameManager.cs Line 874).

Then at client side, after receive spawn network object `Is Owner Client` will be `true` if defined `Client Connection Id` equals to network object `Connection Id` (See LiteNetLibGameManager.cs Line 671).

**Comment by NFMynster** [comment]
Ah that's perfect, I'm familiar with passing along to the connection ID's to define the owner. I will test this out.
Though, you're mentioning that it's still calling a Assets.NetworkSpawn(), does this mean that in-scene objects aren't really initialized in say "Awake()" or at "Start()" in the scene?

I will test none the less, thank you!
