### ISSUE TITLE
Support for child network behaviors

### ISSUE THREAD

**Issue by NFMynster** [insthync/LiteNetLibManager#8]
Support for this would be awesome.

I've basically just made the identity a serialized field, so you gotta drag it in manually on each behavior, but seems like there's more work needed.

Thank you.

**Comment by insthync** [comment]
I will do research then decide to add it or not later

**Comment by NFMynster** [comment]
Awesome!

**Comment by NFMynster** [comment]
@insthync Did you ever get around having a look at this? 🥇

**Comment by insthync** [comment]
Yes, just pushed to the repository you can try it, now you can add child behaviours but its root must attach `LiteNetLibIdentity`

**Comment by NFMynster** [comment]
Perfect, I was missing the setup part, I'll test when I get home.

**Comment by NFMynster** [comment]
Ah, aren't you forgetting not setting the identity? It could just be a serialized field so you can drag the root identity on there.
https://github.com/insthync/LiteNetLibManager/blob/master/Scripts/GameApi/LiteNetLibBehaviour.cs#L82

**Comment by insthync** [comment]
Yes, you're right. I just pushed the update.
